-- Deprecated legacy extension snapshot.
-- Optional demo data is now owned by:
--   scripts/seed-data.js
--
-- Use:
--   npm run seed:db -- --profile=kendari-demo --reset
-- or:
--   npm run seed:demo
